name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # add-start
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    # add-end
    - name: Build app
    # modify-start
    # run: |
    #   npm install
    #   npm run build
    #   echo $(ls -1 .)
      run: |
        dotnet build LearnApi/LearnApi.sln --no-restore
        echo $(ls -1 .)
    # modify-end
    - name: Build the Docker image
      run: |
        docker build -t lymims/learn-api -f LearnApi/LearnApi/Dockerfile .
        echo $(ls -1 .)
    - name: Login to Registry
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}
    - name: Push Image
      run: |
        docker push lymims/learn-api
